# syntax=docker/dockerfile:1
# Multi stage Build

# Build stage I : We need it to build th app
FROM openjdk:11 AS BUILD

COPY . /src
WORKDIR /src


# Build stage II : Run the App on the JVM
ENTRYPOINT []
EXPOSE 5001